#!/usr/bin/env sh
set -eu

env | awk -F= '
    $1 ~ /^(CODEX_|OPENAI_|GH_|GITHUB_|LINEAR_|ANTHROPIC_|AZURE_OPENAI_|OPENROUTER_)/ ||
    $1 ~ /^(GIT_EDITOR|VISUAL|EDITOR|BROWSER|DEBUG|PAGER|GLAMOUR_STYLE|NO_COLOR|CLICOLOR|CLICOLOR_FORCE|DO_NOT_TRACK)$/ ||
    $1 ~ /^(HTTP_PROXY|HTTPS_PROXY|NO_PROXY|ALL_PROXY|SSL_CERT_FILE|SSL_CERT_DIR|REQUESTS_CA_BUNDLE|CURL_CA_BUNDLE)$/ {
        print "--env", $1
    }
'
